### ISSUE TITLE
Add yatiml to conda-forge

### ISSUE THREAD

**Issue by svenvanderburg** [yatiml/yatiml#37]
As a maintainer of a package that depends on yatiml I would like to have yatiml added to conda-forge, so my package can be installed through conda. ADditionally adding yatiml to conda would allow data scientists to install yatiml in a way that they are familiar with.

**Comment by svenvanderburg** [comment]
I already submitted a [PR with a conda recipe](https://github.com/conda-forge/staged-recipes/pull/15876) to the conda-forge recipes repo.

**Comment by LourensVeen** [comment]
Makes sense, and could also help mitigate the `ruamel.yaml` vs `ruamel_yaml` fiasco.

**Comment by LourensVeen** [comment]
We need to update the release process to add instructions on propagating a new release to conda-forge. Their instructions are at  https://conda-forge.org/#contribute and our feedstock is at https://github.com/conda-forge/yatiml-feedstock. That conda-smithy generated README says:

> If you would like to improve the yatiml recipe or build a new package version, please fork this repository and submit a PR. Upon submission, your changes will be run on the appropriate platforms to give the reviewer an opportunity to confirm that the changes result in a successful build. Once merged, the recipe will be re-built and uploaded automatically to the conda-forge channel, whereupon the built conda packages will be available for everybody to install and use from the conda-forge channel. Note that all branches in the conda-forge/yatiml-feedstock are immediately built and any created packages are uploaded, so PRs should be based on branches in forks and branches in the main repository should only be used to build distinct package versions.

> In order to produce a uniquely identifiable distribution:

> If the version of a package is not being increased, please add or increase the [build/number](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-number-and-string).
> If the version of a package is being increased, please remember to return the [build/number](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-number-and-string) back to 0.

I'm the maintainer, so I think I can accept my own PR there once it passes the tests. Let's do this for 0.9.0 and take some notes, then update the instructions in development.rst based on that.

**Comment by LourensVeen** [comment]
Also, `docs/installation.rst` should be updated to say that when you're using conda, you should install using `conda install --channel/conda-forge yatiml` instead of using `pip`.

**Comment by LourensVeen** [comment]
Okay, the release process has been updated, and the installation instructions as well. It would have been nice to have the latter included in the release, but I didn't think of it in time. So it'll all go into the next release instead.

**Comment by LourensVeen** [comment]
The release process needed a few tweaks because I reused an existing clone of an existing fork, which didn't have all the updates. So I've added instructions to make that scenario work, which didn't make it into the release (of course). But since that's not user-facing, I'm going to consider this released in 0.10.0.
