### ISSUE TITLE
Empty requirements.txt file; improve contribution guidelines

### ISSUE THREAD

**Issue by maltelueken** [yatiml/yatiml#45]
During the eScience reusabilithon, we noticed that the `requirements.txt` file is empty (although yatiml has two dependencies). It also seems like the file was just included in the 'initial commit' for no specific reason. Would it make sense to just remove the file from the repo?

Otherwise, we were very impressed by the reusability of the package!

**Comment by maltelueken** [comment]
Ok!

Yes, it seems like I don't have permission to add labels indeed.

**Comment by LourensVeen** [comment]
It looks like it's a GitHub feature, you need to have write access to the repository to be able to add a label. It looks like I'm currently the only person with any rights to the repository, which is actually against our rules. (Is that on the reusabilithon checklist? If not, maybe it should be?) So, if you want I can make you a co-owner, and then you can add a label...

**Comment by maltelueken** [comment]
Perhaps you could modify the contribution guidelines then, so that people don't get confused when they are supposed to add a label to their issue?
Of course you can make me a co-owner, but maybe there is a more suitable person for that who has more experience with yaml and python packages?

**Comment by LourensVeen** [comment]
Ah, it was about the contribution guidelines. Those come from the template too, and the template is a wee bit overdesigned with respect to the bureaucracy it sets up. Second system syndrome I guess. If that's still in the template, then maybe it should be removed there too actually.

I'll take this issue as removing requirements.txt and updating/streamlining the contribution guidelines. I'm super busy at the moment with other stuff, but it'll be here and I'll take it along next time I work on YAtiML.

**Comment by LourensVeen** [comment]
Looks like the CONTRIBUTING.rst wasn't actually valid ReStructuredText either... Well, I've removed the request to add labels, and the `requirements.txt` is gone too, so this should be fixed.

**Comment by LourensVeen** [comment]
Released in 0.10.0.
